services:
  spring-boot-app:
    image: openjdk:21
    container_name: card-cost-api
    working_dir: /app
    volumes:
      - ./target/CardCostTest-0.0.1-SNAPSHOT.jar:/app/CardCostTest-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mydatabase
    depends_on:
      - mysql
    command: [ "java", "-jar", "CardCostTest-0.0.1-SNAPSHOT.jar" ]

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
